<a href="https://colab.research.google.com/github/jmlly/Algoritmos/blob/main/Atividades/Atividade-06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
arr3 = np.arange(10, 20, 2)
arr3

array([10, 12, 14, 16, 18])

In [7]:
arr4 = np.arange(10, 20, 1.4)
arr4

array([10. , 11.4, 12.8, 14.2, 15.6, 17. , 18.4, 19.8])

In [8]:
arr5 = np.linspace(10, 20, 11) #11 elementos
arr5

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [9]:
arr6 = np.linspace(10, 20, 101) #criou 101 elementos do 10 ao 20
arr6

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [10]:
arr7 = np.linspace(0, np.pi, 100) #100 elementos do 0 ao pi
arr7

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [11]:
minhaMatriz = np.array([[1,2,3], 
                        [4,5,6]]) #criando uma matriz

In [12]:
minhaMatriz = np.array([[1,2,3], [4,5,6]]) 
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
minhaLista = [[13,81,22], [0, 34, 59], [21, 48, 94]] #criando uma matriz a partir de uma lista

In [14]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

np.zeros: pode formar vetores e matrizes

In [16]:
x = np.zeros(3) #vetor
x

array([0., 0., 0.])

In [17]:
x = np.zeros((3,2)) #matriz
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

criando sem salvar em variáveis:

In [18]:
print(np.zeros(3)) #vetor

[0. 0. 0.]


In [19]:
print(np.zeros((3, 2))) #matriz

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

### Desafio: como obter uma matriz 4x4 apenas com
números 8?

In [32]:
print(np.full((4,4),[8]))

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [25]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6])) #posicionando os numeros na diagonal
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [29]:
y = np.eye(5) #uma matriz 5x5 com 1 na diagonal
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
y = np.eye(5, dtype= int) #transformando o tipo de float para inteiro
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.shape(minhaMatriz) #verificando a quantidade de linhas e colunas da matriz

(3, 3)

In [34]:
minhaMatriz.shape #outra maneira de verificar

(3, 3)

In [35]:
type(minhaMatriz) #tipo da matriz

numpy.matrix

In [36]:
minhaMatriz.dtype

dtype('int64')

dtype é a abreviação de data typee é usado no numpy e biblitoecas numéricas/científicas correlatas para identificar o tipo de dados que estará contido num objeto.

In [38]:
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [37]:
minhaMatriz[2, 1] #selecionando os elementos da matriz (lembrando que o indice começa a contagem no 0)

48

Selecionando a primeira linha da matriz:

In [39]:
print(minhaMatriz[0,:])

[[13 81 22]]


Selecionando a terceira coluna da matriz:

In [40]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


Alterando um elemento da matriz:

In [41]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

Obtendo a soma dos valores do array:

In [47]:
meuArray = np.array([13,81,22,100,34,59,21,48,94])

In [48]:
np.sum(meuArray)

472

Obtendo o produto:

In [49]:
np.prod(meuArray)

440321981299200

Obtendo a soma acumulada:

In [50]:
np.cumsum(meuArray) #soma um numero com o resultado da soma anterior

array([ 13,  94, 116, 216, 250, 309, 330, 378, 472])

Obtendo o valor mínimo do array:

In [52]:
meuArray.min()

13

Obtendo o valor máximo:

In [53]:
meuArray.max()

100

Obtendo a média dos valores do array:

In [54]:
np.mean(meuArray)

52.44444444444444

Obtendo a mediana:

In [55]:
np.median(meuArray)

48.0

Obtendo a variância dos valores:

In [56]:
np.var(meuArray)

964.246913580247

Obtendo o desvio padrão dos valores:

In [57]:
np.std(meuArray)

31.052325413409008

### Desafio

Criar um array unidimensional usando arange com 20 elementos;

● “Varrer” o array para obter os pares;

● “Varrer” o array para obter os ímpares;

● Obter a média, a soma, o produto, a variância e o desvio padrão
do array.

● Saber se os valores são maiores que 5;

● Obter os valores maiores que 5.

In [58]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
pares = np.delete(array,array[1::2])
pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [74]:
impares = np.delete(array,array[::2])
impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
np.mean(array)

9.5

In [64]:
array.sum()

190

In [65]:
array.prod()

0

In [66]:
np.var(array)

33.25

In [67]:
np.std(array)

5.766281297335398

In [79]:
print(array > 5)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [87]:
x= np.delete(array,array[0:6])
print(x)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
